# Generated by Django 4.1.1 on 2022-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status', models.CharField(max_length=100)),
                ('other_states', models.CharField(max_length=100)),
                ('number_of_siblings', models.IntegerField()),
                ('estimated_income', models.IntegerField()),
                ('estimated_expenses', models.IntegerField()),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_address', models.IntegerField()),
                ('f_phone_number', models.IntegerField()),
                ('father_employment', models.CharField(max_length=100)),
                ('father_income', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_address', models.IntegerField()),
                ('m_phone_number', models.IntegerField()),
                ('mother_employment', models.CharField(max_length=100)),
                ('mother_income', models.CharField(max_length=100)),
                ('guardian_full_name', models.CharField(max_length=100)),
                ('guardian_address', models.IntegerField()),
                ('g_phone_number', models.IntegerField()),
                ('guardian_employment', models.CharField(max_length=100)),
                ('guardian_income', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('ID_NO_passport', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100)),
                ('campus_branch', models.CharField(max_length=100)),
                ('faculty_branch', models.CharField(max_length=100)),
                ('course_study', models.CharField(max_length=100)),
                ('mode_study', models.CharField(max_length=100)),
                ('class_year', models.IntegerField()),
                ('course_duration', models.IntegerField()),
                ('year_completion', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('physical_address', models.IntegerField()),
                ('permanent_address', models.IntegerField()),
                ('institution_post_address', models.IntegerField()),
                ('institution_tel_phone', models.IntegerField()),
                ('amount_applied', models.IntegerField()),
            ],
        ),
    ]
